---

- name: public key
  apt_key: 
    id: 6A26B1AE64C3C388
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: mongo repo
  apt_repository: 
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse"
    state: present                                      
- name: install packages
  apt: 
    pkg: mongodb-org 
    state: present
    update_cache: yes