---


# erlang

# 
    # update_cache: yes
  
# rabbitmq


# - name: command 0
#   shell: sudo apt-get install curl gnupg apt-transport-https -y

# - name: main sign key
#   shell: curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

# - name: ppa erlang
#   shell: curl -1sLf "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg > /dev/null

# - name: rabbitmq repo
#   shell: curl -1sLf "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/io.packagecloud.rabbitmq.gpg > /dev/null
# - name: my string 
#   shell: mkdir {{ mystring }}

# - name: create file
#   shell: 

- name: add content to file
  shell: sudo echo {{ rabbitmq }}>>/etc/apt/sources.list.d/rabbitmq.list