--- 
- name: curl installation
  apt:
    name: curl
    state: present
    # update_cache: yes

- name: install net-tools
  apt: 
    name: net-tools
    state: present
    # update_cache: yes

- name: vim editor
  apt: 
    name: vim
    state: present
    # update_cache: yes